import {
  Baby,
  UserMinus,
  Globe,
  Users,
  CreditCard,
  Move,
  Home,
} from "lucide-react";
import { ASSETS } from "@/lib/constants/assets";

export const availableServices = [
  {
    id: "change-of-hoh",
    title: "Change of Head of Household",
    description: "Apply to change the head of household in your family record",
    image: ASSETS.images.changeOfHoH,
    color: "bg-primary",
    link: "/services/change-of-hoh",
    icon: Home,
  },
  {
    id: "nationality-certificate",
    title: "Nationality Certificate",
    description: "Apply for a nationality certificate ",
    image: ASSETS.images.nationalityCertificate,
    color: "bg-primary",
    link: "/services/nationality-certificate",
    icon: Baby,
  },
  {
    id: "birth-registration",
    title: "Birth Registration",
    description: "Register a new birth and obtain a birth certificate",
    image: ASSETS.images.birth,
    color: "bg-primary",
    link: "/services/birth-registration",
    icon: Baby,
  },
  {
    id: "death-registration",
    title: "Death Registration",
    description: "Register a death and obtain a death certificate",
    image: ASSETS.images.death,
    color: "bg-primary",
    link: "/services/death-registration",
    icon: UserMinus,
  },
  {
    id: "cid-issuance",
    title: "CID Issuance",
    description: "Apply for new CID, renewal, or replacement",
    image: ASSETS.images.cidIssuance,
    color: "bg-primary",
    link: "/services/cid-issuance",
    icon: CreditCard,
  },
  {
    id: "relationship-services",
    title: "Relationship",
    description: "Apply for a relationship certificate.",
    image: ASSETS.images.relationship,
    color: "bg-primary",
    link: "/services/relationship",
    icon: Users,
  },
  {
    id: "move-in-move-out",
    title: "Move In/Move Out",
    description: "Register residential movement within Bhutan",
    image: ASSETS.images.moveInMoveOut,
    color: "bg-primary",
    link: "/services/move-in-move-out",
    icon: Move,
  },
  {
    id: "naturalization",
    title: "Naturalization & Regularization",
    description: "Citizenship pathways and residency regularization",
    image: ASSETS.images.naturalization,
    color: "bg-primary",
    link: "/services/naturalization-regularization",
    icon: Globe,
  },
];
